import type { SidebarsConfig } from "@docusaurus/plugin-content-docs"

const sidebars: SidebarsConfig = {
	tutorialSidebar: [
		"index",
		{
			type: "category",
			label: "Getting Started",
			items: [
				"getting-started/installing",
				"getting-started/concepts",
				{
					type: "doc",
					id: "getting-started/setting-up",
					label: "Setup",
				},
				"getting-started/your-first-task",
			],
		},
		{
			type: "category",
			label: "Using Kilo Code",
			items: [
				"basic-usage/the-chat-interface",
				"basic-usage/model-selection-guide",
				"basic-usage/using-modes",
				"basic-usage/autocomplete",
				"basic-usage/context-mentions",
				{
					type: "category",
					label: "Basic Features",
					items: [
						"basic-usage/orchestrator-mode",
						"basic-usage/task-todo-list",
						"basic-usage/git-commit-generation",
						"features/browser-use",
						"features/code-actions",
						"features/system-notifications",
						"features/more-features",
					],
				},
				{
					type: "category",
					label: "AI Model Providers",
					items: [
						"basic-usage/connecting-providers",
						"getting-started/connecting-api-provider",
						"features/api-configuration-profiles",
						"providers/kilocode",
						{
							type: "category",
							label: "Other Providers",
							items: [
								"providers/anthropic",
								"providers/bedrock",
								"providers/cerebras", // kilocode_change
								"providers/chutes-ai",
								"providers/claude-code",
								"providers/deepseek",
								"providers/fireworks",
								"providers/gemini",
								"providers/glama",
								"providers/groq",
								"providers/human-relay",
								"providers/inception", // kilocode_change
								"providers/lmstudio",
								"providers/minimax", // kilocode_change (M2 model update)
								"providers/mistral",
								"providers/moonshot", // kilocode_change
								"providers/ollama",
								"providers/openai",
								"providers/openai-compatible",
								"providers/openrouter",
								"providers/ovhcloud", // kilocode_change
								"providers/requesty",
								"providers/synthetic", // kilocode_change
								"providers/unbound",
								"providers/v0",
								"providers/vercel-ai-gateway",
								"providers/vertex",
								"providers/virtual-quota-fallback",
								"providers/vscode-lm",
								"providers/xai",
							],
						},
					],
				},
				"basic-usage/adding-credits",
				"basic-usage/settings-management",
			],
		},
		{
			type: "category",
			label: "Core Concepts",
			items: [
				"features/auto-approving-actions",
				"features/suggested-responses",
				"basic-usage/how-tools-work",
				"features/enhance-prompt",
				"features/checkpoints",
				"tips-and-tricks",
			],
		},
		{
			type: "category",
			label: "Kilo Paid Plans",
			items: [
				"plans/about",
				"plans/getting-started",
				"plans/dashboard",
				"plans/analytics",
				{
					type: "category",
					label: "AI Adoption Dashboard",
					items: [
						"plans/adoption-dashboard/overview",
						"plans/adoption-dashboard/understanding-your-score",
						"plans/adoption-dashboard/improving-your-score",
						"plans/adoption-dashboard/for-team-leads",
					],
				},
				"plans/team-management",
				"plans/custom-modes",
				"plans/billing",
				{
					type: "category",
					label: "Enterprise-Only Features",
					items: ["plans/enterprise/SSO", "plans/enterprise/model-access", "plans/enterprise/audit-logs"],
				},
				"plans/migration",
			],
		},
		{
			type: "category",
			label: "Agent Behavior",
			items: [
				"agent-behavior/prompt-engineering",
				"agent-behavior/agents-md",
				"agent-behavior/custom-modes",
				"agent-behavior/custom-rules",
				"agent-behavior/custom-instructions",
				"agent-behavior/workflows",
				"agent-behavior/skills",
			],
		},
		{
			type: "category",
			label: "Advanced Usage",
			items: [
				"advanced-usage/migrating-from-cursor-windsurf",
				{
					type: "category",
					label: "Advanced Context Features",
					items: [
						"advanced-usage/memory-bank",
						"features/codebase-indexing",
						"advanced-usage/large-projects",
					],
				},
				{
					type: "category",
					label: "Advanced AI Features",
					items: [
						"features/fast-edits",
						"features/model-temperature",
						"advanced-usage/rate-limits-costs",
						"advanced-usage/free-and-budget-models",
						"features/footgun-prompting",
					],
				},
				"features/auto-launch-configuration",
				"advanced-usage/auto-cleanup",
				"advanced-usage/integrations",
				"advanced-usage/slackbot",
				"advanced-usage/appbuilder",
				"advanced-usage/cloud-agent",
				"advanced-usage/code-reviews",
				"advanced-usage/deploy",
				"advanced-usage/managed-indexing",
				"advanced-usage/agent-manager",
				"advanced-usage/sessions",
				"features/experimental/experimental-features",
			],
		},
		{
			type: "category",
			label: "Extending Kilo Code",
			items: [
				"advanced-usage/local-models",
				{
					type: "category",
					label: "Model Context Protocol (MCP)",
					items: [
						"features/mcp/overview",
						"features/mcp/using-mcp-in-kilo-code",
						"features/mcp/using-mcp-in-cli",
						"features/mcp/what-is-mcp",
						"features/mcp/server-transports",
						"features/mcp/mcp-vs-api",
					],
				},
				"features/shell-integration",
			],
		},
		{
			type: "category",
			label: "Contributing",
			items: [
				"contributing/index",
				"contributing/development-environment",
				{
					type: "category",
					label: "Architecture",
					items: [
						{
							type: "doc",
							id: "contributing/architecture/index",
							label: "Overview",
						},
						"contributing/architecture/annual-billing",
						"contributing/architecture/enterprise-mcp-controls",
						"contributing/architecture/onboarding-engagement-improvements",
						"contributing/architecture/organization-modes-library",
						"contributing/architecture/security-reviews",
						"contributing/architecture/track-repo-url",
						"contributing/architecture/vercel-ai-gateway",
						"contributing/architecture/voice-transcription",
					],
				},
			],
		},
		{
			type: "category",
			label: "Tools Reference",
			items: [
				"features/tools/tool-use-overview",
				"features/tools/access-mcp-resource",
				"features/tools/apply-diff",
				"features/tools/ask-followup-question",
				"features/tools/attempt-completion",
				"features/tools/browser-action",
				"features/tools/delete-file",
				"features/tools/execute-command",
				"features/tools/list-code-definition-names",
				"features/tools/list-files",
				"features/tools/new-task",
				"features/tools/read-file",
				"features/tools/search-files",
				"features/tools/switch-mode",
				"features/tools/update-todo-list",
				"features/tools/use-mcp-tool",
				"features/tools/write-to-file",
			],
		},
		"cli",
	],
}

export default sidebars
