const DEFAULT_MAX_TOKENS = 4096
const DEFAULT_CONTEXT_LENGTH = 32_768
const DEFAULT_PRUNING_LENGTH = 128000

export enum NEXT_EDIT_MODELS {
	MERCURY_CODER = "mercury-coder",
	INSTINCT = "instinct",
}

export { DEFAULT_CONTEXT_LENGTH, DEFAULT_MAX_TOKENS, DEFAULT_PRUNING_LENGTH }
